[package]
name = "conforming"
version = "0.1.0"
edition = "2021"

[dependencies]
conforming_macros = { path = "./conforming_macros" }
serde = "1.0.144"
serde_json = "1.0.85"

[dev-dependencies]
pretty_assertions = "1.2.1"
